# API配置文件

openrouter:
  # 从 https://openrouter.ai/keys 获取
  api_key: ""
  
  # 使用 Qwen 2.5 72B
  default_model: "qwen/qwen-2.5-72b-instruct"
  
  # 模型参数
  temperature: 0.3      # 温度：0-1，越高越随机，越低越确定
  max_tokens: 1000      # 最大输出token数
  
  timeout: 30

output:
  output_dir: "analysis_results"
  use_timestamp: true
